spring:
  application:
    name: ai-pdf-qa

  profiles:
    active: docker     # default for local development
    group:
      dev: dev
      docker: docker

# Common settings shared across profiles
server:
  port: 8081

management:
  endpoint:
    env:
      show-values: ALWAYS
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,env

